### ISSUE TITLE
Usage as RDFa template engine

### ISSUE THREAD

**Issue by claudius108** [nbittich/graph-rdfa-processor#2]
Hi,

Thank you for this nice library!

I am trying to use it as a RDFa templating engine, see [1].

Do you think that it can out put the path of nodes like "/1/2/2/2/1/1/1/1/1/1", in comments, as it is mentioned in [1]?

Thanks,
Claudius Teodorescu

[1] https://ceur-ws.org/Vol-905/BattleEtAl_COLD2012.pdf

**Comment by nbittich** [comment]
Hello, 

Thank you for your output, I'll have a look to the paper next week and will let you know. If you have examples where the output is not as you'd expect, do not hesitate to comment on this issue :)

**Comment by nbittich** [comment]
If you'd  still like to use this library for your work, feel free to reopen the issue and give me examples
